/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as FavoritRouteImport } from './routes/favorit'
import { Route as BelanjaRouteImport } from './routes/belanja'
import { Route as IndexRouteImport } from './routes/index'

const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritRoute = FavoritRouteImport.update({
  id: '/favorit',
  path: '/favorit',
  getParentRoute: () => rootRouteImport,
} as any)
const BelanjaRoute = BelanjaRouteImport.update({
  id: '/belanja',
  path: '/belanja',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/belanja': typeof BelanjaRoute
  '/favorit': typeof FavoritRoute
  '/pengaturan': typeof PengaturanRoute
  '/planner': typeof PlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/belanja': typeof BelanjaRoute
  '/favorit': typeof FavoritRoute
  '/pengaturan': typeof PengaturanRoute
  '/planner': typeof PlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/belanja': typeof BelanjaRoute
  '/favorit': typeof FavoritRoute
  '/pengaturan': typeof PengaturanRoute
  '/planner': typeof PlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/belanja' | '/favorit' | '/pengaturan' | '/planner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/belanja' | '/favorit' | '/pengaturan' | '/planner'
  id: '__root__' | '/' | '/belanja' | '/favorit' | '/pengaturan' | '/planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BelanjaRoute: typeof BelanjaRoute
  FavoritRoute: typeof FavoritRoute
  PengaturanRoute: typeof PengaturanRoute
  PlannerRoute: typeof PlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorit': {
      id: '/favorit'
      path: '/favorit'
      fullPath: '/favorit'
      preLoaderRoute: typeof FavoritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belanja': {
      id: '/belanja'
      path: '/belanja'
      fullPath: '/belanja'
      preLoaderRoute: typeof BelanjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BelanjaRoute: BelanjaRoute,
  FavoritRoute: FavoritRoute,
  PengaturanRoute: PengaturanRoute,
  PlannerRoute: PlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
